@startuml


[-> PicYaPaletteActivity: onCreate
activate PicYaPaletteActivity

create ImageChooserActivity
PicYaPaletteActivity -> ImageChooserActivity:  startActivity

activate ImageChooserActivity
deactivate PicYaPaletteActivity

ImageChooserActivity -> ImageChooserActivity: openSettings
activate ImageChooserActivity

create SettingsActivity
ImageChooserActivity -> SettingsActivity: startActivity
deactivate ImageChooserActivity
deactivate ImageChooserActivity
activate SettingsActivity

SettingsActivity -> SettingsActivity : savePreferences

SettingsActivity --> ImageChooserActivity
deactivate SettingsActivity
activate ImageChooserActivity
<--ImageChooserActivity
deactivate ImageChooserActivity

@enduml