@startuml

User --> (Take Pic)
User --> (Choose Pic)
User --> (Random Palette)
User --> (View Favorites)
User --> (Change Settings)

(Take Pic) --> (View Generated Palettes) : include
(Choose Pic) --> (View Generated Palettes) : include
(Random Palette) --> (View Generated Palettes) : include
(View Generated Palettes) -> (Palette Details) : include
(View Favorites) --> (Palette Details) : include

@enduml