package edu.auburn.eng.csse.comp3710.team8;

import android.graphics.Color;

/**
 * Palette generated by a "random" algorithm. Probably pretty ugly.
 */
public class RandomPalette extends Palette {
    public RandomPalette(int primary) {
        super(primary);
        // Generate secondary and tertiary colors!

    }

    public RandomPalette(int primary, int secondary) {
        super(primary, secondary);
        // Generate tertiary colors!

    }

    public RandomPalette(int primary, int secondary, int tertiary) {
        super(primary, secondary, tertiary);
    }

    @Override
    public int generateColor(int[] colorsIn) {
        return 0;
    }
}
